name: FTP_Deploy_Portfolio

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.etanepal.com
          port: 21
          username: cicdtest@test.etanepal.com
          password: X9v!qT7r#Lp2Zf
          local-dir: ./
          server-dir: /home/etanepal/test.etanepal.com/
          protocol: ftp
          security: loose

