name: SFTP_Deploy_Portfolio

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SCP (SFTP over SSH)
        uses: appleboy/scp-action@v1
        with:
          host: ftp.etanepal.com
          username: cicdtest
          password: X9v!qT7r#Lp2Zf
          port: 22
          source: "./*"
          target: "/home/etanepal/test.etanepal.com/"
          rm: false
